---
- name: install base-devel package (breaks manjaro)
  pacman: name=base-devel
  when: ansible_distribution == 'Antergos' or ansible_distribution == 'Archlinux'
  tags:
  - boot

- name: install essential packages (this may take a while)
  pacman: name="{{ item }}"
  with_items:
  - bc
  - btrfs-progs
  - efibootmgr
  - grub
  - intel-ucode
  - kmod
  - libelf
  - openssl-1.0 
  - os-prober
  tags:
  - boot

- name: remove unused kernels
  pacman:
    name: "{{ item }}"
    state: absent
  with_items:
  - linux
  - linux-lts
  failed_when: false
  tags:
  - boot

- name: set initrd modules
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES='
    line: 'MODULES="btusb pwm-lpss pwm-lpss-platform"'
  notify:
  - update boot
  tags:
  - boot

- name: set HOOKS for chrooted system (iso creation = yes)
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS='
    line: 'HOOKS="base udev memdisk archiso_shutdown archiso archiso_loop_mnt archiso_pxe_common archiso_pxe_nbd archiso_pxe_http archiso_pxe_nfs archiso_kms block modconf filesystems keyboard"'
    create: yes
  when: chroot == true
  notify:
  - update boot
  tags:
  - boot

- name: set HOOKS for running system (iso creation = no)
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS='
    line: 'HOOKS="base systemd block btrfs autodetect modconf filesystems fsck"'
    create: yes
  when: chroot == false
  notify:
  - update boot
  tags:
  - boot