---
- name: create systemd sleep directory
  file:
    path: /lib/systemd/system-sleep
    state: directory
  tags:
  - fan
  - power

- name: copy gpd-fan files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
  - { src: 'files/gpd-fan.conf', dest: '/etc/gpd/fan.conf', mode: '0644' }
  - { src: 'files/gpd-fan.py', dest: '/usr/local/sbin/gpd-fan', mode: '0777' }
  - { src: 'files/gpd-fan.service', dest: '/etc/systemd/system/gpd-fan.service', mode: '0644' }
  - { src: 'files/gpd-fan.sh', dest: '/lib/systemd/system-sleep/gpd-fan', mode: '0777' }
  notify:
  - enable gpd-fan
  tags:
  - fan
  - power