---
- include: arch.yml
  when: ansible_distribution == 'Antergos' or ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjaro Linux'

- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Kali' or ansible_distribution == 'Linuxmint' or ansible_distribution == 'Ubuntu'

- include: fedora.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat'

- include: gentoo.yml
  when: ansible_distribution == 'Gentoo'

- name: create chtrt5645 directory
  file:
    path: /usr/share/alsa/ucm/chtrt5645
    state: directory
  tags:
  - audio

- name: copy audio config files to device
  copy:
    src: "{{ item }}"
    dest: /usr/share/alsa/ucm/chtrt5645/
    owner: root
    group: root
    mode: 0644
  with_items:
  - files/chtrt5645.conf
  - files/HiFi.conf
  tags:
  - audio

- name: set default sink and source in pulseaudio
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: "^{{ item.key }} "
    line: "{{ item.key }} {{ item.value}}"
  with_items:
  - { key: 'set-card-profile', value: 'alsa_card.platform-cht-bsw-rt5645 HiFi' }
  - { key: 'set-default-sink', value: 'alsa_output.platform-cht-bsw-rt5645.HiFi__hw_chtrt5645__sink' }
  - { key: 'set-sink-port', value: 'alsa_output.platform-cht-bsw-rt5645.HiFi__hw_chtrt5645__sink [Out] Speaker' }
  tags:
  - audio

- name: disable pulse realtime scheduling
  lineinfile:
    path: /etc/pulse/daemon.conf
    line: 'realtime-scheduling = no'
  tags:
  - audio
  
- name: remove old realtime scheduling line (if present)
  lineinfile:
    path: /etc/pulse/daemon.conf
    regexp: '^realtime-scheduling = yes'
    state: absent
  tags:
  - audio